@extends('layouts.app')

@section('title', 'Selección de asientos')

@push('styles')
  <link rel="stylesheet" href="{{ asset('css/asiento.css') }}">
@endpush

{{-- No footer on this time-sensitive page --}}
@section('footer')@endsection

@section('content')

<div class="cb-back-bar">
  <a href="{{ route('peliculas.show', $pelicula->id) }}" class="cb-back">&#8592; Volver</a>
  <span class="cb-timer" id="cronometro">10:00</span>
</div>

<h2 class="asientos-title">{{ $pelicula->titulo }}</h2>

<div class="pantalla-wrapper">
  <div class="pantalla"></div>
  <p class="pantalla-label">Pantalla</p>
</div>

<form method="POST" action="{{ route('asientos.guardar') }}" id="formAsientos">
  @csrf

  @if($errors->has('asientos'))
    <p style="text-align:center;color:#e57a8a;font-size:0.85rem;padding:8px 0;">
      {{ $errors->first('asientos') }}
    </p>
  @endif

  <div class="mapa">
    @php
      $filas   = ['A','B','C','D','E'];
      $numeros = range(1, 10);
    @endphp

    {{-- Column number header --}}
    <div class="fila">
      <h2>&nbsp;</h2>
      @foreach($numeros as $n)
        <span class="numero">{{ $n }}</span>
      @endforeach
    </div>

    @foreach($filas as $fila)
      <div class="fila">
        <h2>{{ $fila }}</h2>
        @foreach($numeros as $n)
          @php
            $codigo     = $fila . $n;
            $estaOcupado = in_array($codigo, $ocupados);
            $esEspecial  = in_array($codigo, $especiales);
            if ($estaOcupado)      $clase = 'ocupado';
            elseif ($esEspecial)   $clase = 'especial';
            else                   $clase = 'disponible';
          @endphp

          @if($estaOcupado)
            <div class="butaca {{ $clase }}" title="{{ $codigo }} — Ocupado"></div>
          @else
            <div class="butaca {{ $clase }}"
                 data-codigo="{{ $codigo }}"
                 data-tipo="{{ $esEspecial ? 'especial' : 'regular' }}"
                 data-precio="{{ $esEspecial ? 55 : 35 }}"
                 title="{{ $codigo }} — Bs. {{ $esEspecial ? 55 : 35 }}"
                 onclick="toggleAsiento(this)"></div>
          @endif
        @endforeach
      </div>
    @endforeach
  </div>

  {{-- Legend --}}
  <div class="Asientos">
    <div class="leyenda-item">
      <div class="cuadro" style="background:#3A3A3A;"></div>Disponible — Bs. 35
    </div>
    <div class="leyenda-item">
      <div class="cuadro" style="background:#27AE60;"></div>Seleccionado
    </div>
    <div class="leyenda-item">
      <div class="cuadro" style="background:#C0392B;"></div>Ocupado
    </div>
    <div class="leyenda-item">
      <div class="cuadro" style="background:#2471A3;"></div>VIP — Bs. 55
    </div>
  </div>

  {{-- Summary panel (hidden until a seat is selected) --}}
  <div class="resumen" id="resumen" style="display:none;">
    <p>Asientos <strong id="txtAsientos">—</strong></p>
    <p>Subtotal entradas <strong id="txtSubtotal">Bs. 0</strong></p>
    <p class="resumen-total">Total <strong id="txtTotal">Bs. 0</strong></p>
  </div>

  {{-- Hidden seat inputs are generated by JS --}}
  <div id="inputsOcultos"></div>

  <div style="text-align:center;padding:0 16px 40px;">
    <button type="submit" id="btnContinuar"
            class="boton-ver-mas"
            style="max-width:320px;opacity:.4;cursor:not-allowed;"
            disabled>
      Confirmar asientos &rarr;
    </button>
  </div>
</form>

@endsection

@push('scripts')
<script>
  var seleccionados = {};

  function toggleAsiento(el) {
    var codigo = el.dataset.codigo;
    var precio = parseInt(el.dataset.precio);
    var tipo   = el.dataset.tipo;

    if (seleccionados[codigo]) {
      delete seleccionados[codigo];
      el.classList.remove('seleccionado');
      el.classList.add(tipo === 'especial' ? 'especial' : 'disponible');
    } else {
      if (Object.keys(seleccionados).length >= 8) {
        alert('Máximo 8 asientos por compra.');
        return;
      }
      seleccionados[codigo] = precio;
      el.classList.remove('disponible', 'especial');
      el.classList.add('seleccionado');
    }
    actualizarResumen();
  }

  function actualizarResumen() {
    var codigos = Object.keys(seleccionados);
    var total   = Object.values(seleccionados).reduce(function(a, b){ return a + b; }, 0);

    document.getElementById('txtAsientos').textContent  = codigos.length ? codigos.join(', ') : '—';
    document.getElementById('txtSubtotal').textContent  = 'Bs. ' + total;
    document.getElementById('txtTotal').textContent     = 'Bs. ' + total;
    document.getElementById('resumen').style.display    = codigos.length ? 'block' : 'none';

    // Rebuild hidden inputs
    var container = document.getElementById('inputsOcultos');
    container.innerHTML = '';
    codigos.forEach(function(c) {
      var inp = document.createElement('input');
      inp.type  = 'hidden';
      inp.name  = 'asientos[]';
      inp.value = c;
      container.appendChild(inp);
    });

    var btn = document.getElementById('btnContinuar');
    btn.disabled        = codigos.length === 0;
    btn.style.opacity   = codigos.length ? '1' : '0.4';
    btn.style.cursor    = codigos.length ? 'pointer' : 'not-allowed';
  }

  // Countdown timer — 10 minutes
  (function () {
    var seg = 600;
    var el  = document.getElementById('cronometro');
    var t   = setInterval(function () {
      if (--seg <= 0) {
        clearInterval(t);
        el.textContent = '00:00';
        el.style.color = '#C0392B';
        return;
      }
      var m = Math.floor(seg / 60).toString().padStart(2, '0');
      var s = (seg % 60).toString().padStart(2, '0');
      el.textContent = m + ':' + s;
    }, 1000);
  })();
</script>
@endpush
